version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo
  api:
    container_name: api-container
    image: node:17
    restart: always
    command: bash -c "npm install && npm run debug"
    working_dir: /src
    volumes:
      - ./dist/:/src/dist/
      - ./package.json:/src/package.json
    ports:
      - "8060:8060"
      - "9222:9222"
    networks:
      - mongo
networks:
  mongo: